name: Test Clean Install

on:
  push:
    paths:
      - "**/*.go"

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18' ]
    env:
      MUREX_BUILD_FLAGS: --no-colour
      MUREX_TEST_NO_EXEC_DEPS: true

    steps:

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: |
          go version

      - name: Go Test
        run: |
          go install github.com/lmorg/murex@latest
